### ISSUE TITLE
Multiple languages files

### ISSUE THREAD

**Issue by lukaszflorczak** [leonardovilarinho/vue-multilanguage#1]
Hi. Is it possible to have more than one  files for each language and load them only if a component need them?

I want to use this plugin in project with  thousands of phrases to translate and I don't want to load one big file on start.

**Comment by leonardovilarinho** [comment]
@lukaszflorczak Sorry for the delay in reply, GitHub did not notify me.

I'll be adding this functionality soon, so far it is not possible.

Thanks for the tip :)

**Comment by leonardovilarinho** [comment]
I'm working on it

**Comment by lukaszflorczak** [comment]
Thanks for your reply. I wait and good luck! :)

**Comment by leonardovilarinho** [comment]
50c44bd fix it! It is a new version of the plugin, a lot has changed, languages are no longer in JSON, reactivity without Vuex, languages in JS files that allow division, perfomance is better, without ajax.

**Comment by lukaszflorczak** [comment]
Thanks for update. I have one more question. Is it possible to use it with webpack and have separated language files in a production app? And load it only when the translation is needed?

**Comment by leonardovilarinho** [comment]
Basically it is not possible to do this, because as we now have javascript objects the compiler incorporates all this into a single file.

You can minimize this by using SSR techniques, or by having the webpack separate code files from each page for you.

SSR: http://ssr.vuejs.org/
webpack code splitting: https://webpack.github.io/docs/code-splitting.html

Or improve performance with pre rendering: https://github.com/chrisvfritz/prerender-spa-plugin
