### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by mmoscosa** [leonardovilarinho/vue-multilanguage#22]
Hey Leonardo, first of all awesome plugin!!

when I run `npm run develop` it works perfect, however when am trying to build (`npm run build`) I get the following error:

`ERROR in app.5759ff76dd1a0612ec02.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue-multilanguage/src/vue-multilanguage.js:196,0][app.5759ff76dd1a0612ec02.js:2987,10]`

You can see the video of the error happening here:
https://www.useloom.com/share/626412a7e56b47389f7a116c092deb9d

---

- "nuxt": "^1.0.0-rc11"
- "vue-multilanguage": "^2.2.3"

[Project ](https://github.com/mmoscosa/Bardho)

- [package.json ](https://github.com/mmoscosa/Bardho/blob/master/package.json)
- [nuxt.config.js](https://github.com/mmoscosa/Bardho/blob/master/nuxt.config.js)

**Comment by leonardovilarinho** [comment]
Hi, this error no is in vue-multilanguage, but you can resolve commenting the UglifyJS line in webpack.config.js.

**Comment by FrancescoMussi** [comment]
Great plugin indeed. Simple and efficient.

But I have run into the same exact problem:

```
ERROR in static/js/vendor.57d8ec30172fe67cd491.js from UglifyJs
Unexpected token: punc (() [./~/vue-multilanguage/src/vue-multilanguage.js:196,0][static/js/vendor.57d8ec30172fe67cd491.js:40469,10]

```

And after many attempts, the only thing that fixed the issue was indeed to comment out the UglifyJS lines from webpack.config.js. 

But what exactly is going on here?
In my case it happened after installing vue-multilanguage.
But I see that the same issue is reported on several other github vue components, so most probably is not a fault of any of these.

Is it babel not being up to date with ES2016?

**Comment by jdriesen** [comment]
Hi All,

Ran into the same problem (when building a Vue Project, I'm NOT using Laravel...)

IMHO ... 'commenting out the UglifyJS line in webpack.config.js.' isn't the way to go...
The must be a reason why UglifyJS is mentioned in 'webpack.config.js' no ? 

Why don't other packages have this problem with  UglifyJS ?
(it's just a Q... I don't have that much experience with WebPacks...)

Thanks in advance for your answer.

Kind regards,
Johnny
