### ISSUE TITLE
My current solution + one last question...

### ISSUE THREAD

**Issue by jdriesen** [leonardovilarinho/vue-multilanguage#4]
Hi Leonardo,

As promised, I give you a link to what I have so far…
http://test01.ireporter.be (it’s not that fancy, but feel free to play with it…)

PS.: every component (topmenu, main-menu, main-content and footer) are al listening the a ‘language-changed’ event…

Only problem I’m having…. I can’t set the ‘placeholder’ for the input fields on the ‘login’ form…

Grtz & thanks again for your solution,

Johnny

**Comment by leonardovilarinho** [comment]
Hello,

Just use the vue bind with the `v-bind` directive.

I updated the plugin demo, if you download this repository and run `npm run demo` you can see an example with the placeholder.

In short, just do something like this:

```
<label v-lang.username></label>
<input :placeholder="username" v-model="user.username">

...

computed: {
    username() {
      return this.translate(this.$language, 'username')
    }
  }
```

PS: You can now also delete this language change event. Because by exchanging `$language` for a component, the plguin will change the rest.

**Comment by jdriesen** [comment]
Cool solution !!!

Thanks for the terrific support, Leonardo !

Grtz,
Johnny

**Comment by jaumebalust** [comment]
Hi!
The example is wrong.
Here is how it should be:

`computed: {
    username() {
      return this.translate(this.$language, 'username')
    }
  }`

Cheers,

**Comment by leonardovilarinho** [comment]
Hi @jaumebalust,

this code is for the old version, now you can use:
```
computed: {
  username () {
    return this.translate('username')
  }
}
```
