### ISSUE TITLE
EN is always default language

### ISSUE THREAD

**Issue by boomsya** [leonardovilarinho/vue-multilanguage#48]
```
Vue.use(MultiLanguage, {
	default: 'ua',
	ru: {
		hi: 'тест',
		welcome: 'Bem-vindo, {name}'
	},
	en: {
		hi: 'Hello',
		welcome: 'Welcome, {name}'
	},
	ua: {
		hi: 'привіт',
		welcome: 'Welcome, {name}'
	}
});

console.log(this.language);

```
writes: **en**

**Comment by boomsya** [comment]
anyway thanks. App at now is support multilanguage

**Comment by leonardovilarinho** [comment]
I rewrote the plugin, to give more performance and improve usage. In this new version (> 4) I applied its issue.

But if you want to use version 3, in App.vue set the language again by changing the `language` variable. This problem is due to the fact that it uses the same domain (localhost) in different apps, so it saves the language as one.
