### ISSUE TITLE
Nested components

### ISSUE THREAD

**Issue by jdriesen** [leonardovilarinho/vue-multilanguage#7]
Hi Leonardo,

There is still a problem when changing the language globally.
Especially when you're working with nested components.

I guess there is still a small bug in your recursive function (looping over all components)
I'm also using vue-router... but I don't think that's the problem ...
I've spent about 8 hrs of my time to find this out ...
When I've some time, I will make a demo project to reproduce the bug...

(it seems that this code doesn't set the language globally ...)

`
<button v-lang.language="'PT'" @click="$language = 'pt'"></button>
`

A workaround is using a global Language setter, and picking it up in every component...
(that's what I'm doing right now)

Maybe you can take a look at it when you've some time...

Kind regards,
Johnny Driesen
Belgium

**Comment by leonardovilarinho** [comment]
Hello,

Maybe it is going through a situation that I discouraged in the plugin, the component that is not being translated is the App?

Because I disabled it so that it does not update the App component, because this component was only made to flames other components and did not have HTML element.

If the content that needs to be translated is in the App component, move it to a new component and import that component into the App.


If this is not the case, I look forward to your example.

**Comment by jdriesen** [comment]
Hi,

I will try to make an example for you next week.
It's now Thursday evening in Belgium, and I have a travelday tomorrow/ (have to visit a client)

FYI: Currently, evrt is working by setting a global. (bright, shiny & fast !!)

I will keep you posted !

Grtz,
Johnny
